\documentclass[10pt,a4paper]{article}
\usepackage[brazil]{babel}    % dá suporte para os termos na língua portuguesa do Brasil
\usepackage[utf8]{inputenc}   % dá suporte para caracteres especiais como acentos e cedilha
\usepackage[sc]{mathpazo}     % fonte mais nítida
\usepackage[T1]{fontenc}
\usepackage{geometry}         % definição da página
\geometry{verbose,
tmargin=2.5cm, 
bmargin=2.5cm, 
lmargin=2.5cm, 
rmargin=2.5cm}
\usepackage[urlcolor=blue,
citecolor=red,
colorlinks=true]{hyperref}
\usepackage{url}
%\usepackage{breakurl}
\usepackage{graphicx}
\usepackage{longtable}
\usepackage{float}
\usepackage{parskip}          % separação automática entre parágrafos
\usepackage[round]{natbib}
\usepackage{multirow}
\usepackage{colortbl}
\usepackage{array}
\usepackage{threeparttable}

\setlength\parindent{0pt}
\newcommand{\HRule}{\rule{\linewidth}{0.5mm}}

\begin{document}

\begin{titlepage}
  \begin{center}

  % Title
    \HRule \\[0.4cm]
    {\huge \bfseries Tabela em \LaTeX~para biplot} \\[0.4cm]

    \HRule \\[1.5cm]

    % Autor e usuário
    \begin{minipage}{0.5\textwidth}
      \begin{flushleft} \large
        \emph{Autoria:}\\
        José C. \textsc{Faria} \\
        e Ivan B. \textsc{Allaman}
      \end{flushleft}
    \end{minipage}
    \begin{minipage}{0.4\textwidth}
      \begin{flushright} \large
        \emph{Customização em \LaTeX:} \\
        J. C. \textsc{Faria}
      \end{flushright}
    \end{minipage}

    \vfill

    % Bottom of the page
    {\large \today}

  \end{center}
\end{titlepage}
\vspace{3cm}

\newpage

Exemplo de referência de tabelas: Ver Tabelas
\ref{example_2}, 
\ref{example_3} e
\ref{example_15}.

\newpage

<<tab, echo=FALSE, results='asis'>>=
library(bpca)

##Example 1: The simplest possible
bp <- bpca(iris[-5],
           d=1:2)
lbp <- latex.bpca(bp)
lbp
summary(lbp)

##Example 2: with caption 
bp2 <- bpca(gabriel1971) 

latex.bpca(bp2,
           caption='Biplot gabriel1971 (alignment = centering)',
           label='example_2',
           algtable='\\centering')

## Example 3: Almost worked
latex.bpca(bp,
           caption='Biplot da base de dados iris (aligment = flushright)',
           label='example_3',
           v.partial='Parcial',
           v.accumulated='Acumulada',
           eigenvalues='Autovalores',
           eigenvectors='Autovetores',
           v.retained='Var. retida',
           algtable='\\flushright')

## Example 4: Changing the column first alignment
bp3 <- bpca(gge2003,
            d=1:3)

latex.bpca(bp3,
           caption='Biplot gge2003 (changing the column first alignment)',    
           alg1='r')

## Example 5: Changing the column second alignment
latex.bpca(bp3,
           caption='Biplot gge2003 (changing the column second alignment)',    
           #                  alg2='>{\\\\raggedright}p{0.1cm}')
           alg2='r')

## Example 6: Changing the column alignment with numbers
latex.bpca(bp3,
           caption='Biplot gge2003 (changing the column alignment with numbers)',    
           #                  algnumbers='>{\\\\raggedleft}p{2.2cm}')
           alg1='r',
           alg2='r',
           algnumbers='l')

## Example 7: Changing the header alignment 
latex.bpca(bp3,
           caption='Biplot gge2003 (changing the header alignment)',    
           algheader='r')

## Example 8: I want only two places decimal
latex.bpca(bp3,
           round=2,
           caption='Biplot gge2003', 
           algnumbers='>{\\\\centering}p{2.2cm}',
           pc.label='Principal Component-')

## Example 9: With bold in the header, subheader and variables
latex.bpca(bp3,
           round=2,
           caption='Biplot gge2003 (bold in the header, subheader and variables)',
           eigenvalues='\\\\textbf{Eigenvalues}',
           eigenvectors='\\\\textbf{Eigenvectors}',
           v.retained='\\\\textbf{Variance retained (%)}',
           v.partial='\\textbf{Partial}',
           v.accumulated='\\textbf{Accumulated}',
           ft.variable='bold',
           ft.components='bold')  

## Example 10: Changing the font
latex.bpca(bp3,
           round=2,
           caption='Biplot gge2003 (changing the font)', 
           pc.label='\\\\textbf{P. Component-}',           
           size='\\scriptsize')                     

## Example 11: Italic in the variables names
latex.bpca(bp2,
           round=2,
           caption='Biplot gabriel1971 (italic in the variables names)',     
           pc.label='\\\\textbf{Principal Component-}',
           algnumbers='>{\\\\centering}p{2.5cm}',
           ft.variable='italic') 

## Example 12: With footnote
latex.bpca(bp2,   
           round=3,
           caption='Biplot gabriel1971 (with footnote)',     
           footnote='$^1$\\\\scriptsize Example with footnote')

## Example 13: With others principal components
bp4 <- bpca(gabriel1971,
            d=2:4)

latex.bpca(bp4,
           round=5,
           caption='Biplot gabriel1971 (with principal components 2, 3 and 4)')

## Example 14: More than one bpca object
data(marina)

y_2007 <- subset(marina,
                 year==2007)

y_2008 <- subset(marina,
                 year==2008)

y_2009 <- subset(marina,
                 year==2009)   

bp_2007 <- bpca(y_2007[,-c(1:2)],
                d=1:3)

bp_2008 <- bpca(y_2008[,-c(1:2)],
                d=1:2) 

bp_2009 <- bpca(y_2009[,-c(1:2)],
                d=1:2)      

latex.bpca(list(bp_2007,
                bp_2008),
           round=2,
           caption='Biplot Marina (more than one bpca)',
           bpca.label=paste('Year',
                            2007:2008,
                            sep='-'),
           size='\\scriptsize')

## Example 15: With two lines in the table
latex.bpca(list(bp_2007,
                bp_2008,
                bp_2009),
           round=3,
           caption='Biplot Marina (with two lines)',
           label='example_15',
           bpca.label=c('2007','2008','2009'),
           hline1='\\hline \\hline',
           hline2='\\hline \\hline',
           algnumbers='>{\\\\raggedleft}p{1.3cm}',
           size='\\scriptsize',
           footnote='Note: F - Movie; D - Documentary; DH - Documentary directed by men; DF - Documentary directed by women.'
           )  
@

\end{document}
